common:
    lid_topic: "/velodyne_points" 
    imu_topic: "/IMU_data" 
    small_update_max_iterations: 1  # 小更新的最大迭代次数
    bigupdate_max_iterations: 2     # 大更新的最大迭代次数
    small_update_interval: 0.03     # 小更新时间间隔（秒）
    con_frame: false # true: if you need to combine several LiDAR frames into one
    con_frame_num: 1 # the number of frames combined
    cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
    cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency   
    time_diff_lidar_to_imu: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)
    pre_thresh_1: 0.000043
    pre_thresh_2: 0.000041
    pre_thresh_3: 0.000041
    pre_thresh_4: 0.000034
    pre_thresh_5: 0.000035
    pre_thresh_6: 0.000035
    pre_thresh_smooth_coeff: 0.7
preprocess:
    lidar_type: 2
    scan_line: 32
    timestamp_unit: 0           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2.0 
seg:
    linearity_thre: 0.5
    planarity_thre: 0.5
    curvature_thre: 0.1
    beam_direction_ang: 40
    pillar_direction_ang: 50
    roof_normal_ang: 60
    facade_normal_ang: 40
    cloud_pca_neigh_k_min: 4
    cloud_pca_neigh_k: 15
    cloud_pca_neigh_r: 2 
mapping:
    imu_en: true
    extrinsic_est_en: false # for aggressive motion, set this variable false
    imu_time_inte: 0.01 # = 1 / frequency of IMU
    lidar_time_inte: 0.1
    satu_acc: 30.0 # the saturation value of IMU's acceleration. not related to the units
    satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
    acc_norm: 9.7946 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
    lidar_meas_cov: 0.01 # 0.001
    acc_cov_output: 500
    gyr_cov_output: 1000 
    b_acc_cov: 1.2745088891072094e-04
    b_gyr_cov: 6.1767472101311034e-06
    imu_meas_acc_cov: 0.1 #0.1 # 2
    imu_meas_omg_cov: 0.1 #0.1 # 2 
    gyr_cov_input: 2.3503716891509098e-04 # for IMU as input model
    acc_cov_input: 5.1047775589866716e-03 # for IMU as input model
    plane_thr: 0.1 # 0.05, the threshold for plane criteria, the smaller, the flatter a plane
    match_s: 81
    ivox_grid_resolution: 2.0
    dis_thre: 5.0 # 最近邻搜索的距离阈值
    gravity: [0.0, 0.0, -9.7946] # [-0.30, 0.880, -9.76] # liosam [0.0, 9.810, 0.0] # # preknown gravity, use when imu_en is false or start from a non-stationary state
    gravity_init: [0.0, 0.0, -9.7946] # preknown gravity in the initial IMU frame for unstationary start or in the initial LiDAR frame for using without IMU
    extrinsic_T: [ 0.021, -0.22, 1.39036 ]
    extrinsic_R: [ 0.0356581, -0.999341,  -0.00671807,
                  0.999364,  0.0356532,  0.000837854,
                   -0.000597781, -0.00674367,  0.999977]
    # extrinsic_T: [ 0, 0, 0.28] # ulhk # [-0.5, 1.4, 1.5] # utbm
    # extrinsic_R: [ 0, 1, 0,
    #                -1, 0, 0,
    #                0, 0, 1 ] # ulhk 5 6
    # extrinsic_R: [ 0, -1, 0,
    #                 1, 0, 0,
    #                 0, 0, 1 ] # utbm 1, 2
    #extrinsic_R: [ 1, 0, 0,
    #               0, 1, 0,
    #               0, 0, 1 ] # ulhk 4 utbm 3

odometry: 
    publish_odometry_without_downsample: false

publish:
    path_en: true                 # false: close the path output
    dense_publish_en: true        # true: use dense undistorted cloud for publishing
    scan_publish_en: true         # false: close all the point cloud output
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
