common:
    lid_topic: "/points_raw" 
    imu_topic: "/imu_raw" 
    small_update_max_iterations: 2  # 小更新的最大迭代次数
    bigupdate_max_iterations: 2     # 大更新的最大迭代次数
    small_update_interval: 0.02     # 小更新时间间隔（秒）
    con_frame: false # true: if you need to combine several LiDAR frames into one
    con_frame_num: 1 # the number of frames combined
    cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
    cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency   
    time_diff_lidar_to_imu: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)
    pre_thresh_1: 0.000043
    pre_thresh_2: 0.000041
    pre_thresh_3: 0.000041
    pre_thresh_4: 0.000034
    pre_thresh_5: 0.000035
    pre_thresh_6: 0.000035

preprocess:
    lidar_type: 2
    scan_line: 64
    timestamp_unit: 2           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2.0 

mapping:
    imu_en: true
    extrinsic_est_en: false # for aggressive motion, set this variable false
    imu_time_inte: 0.01 # = 1 / frequency of IMU
    lidar_time_inte: 0.1
    satu_acc: 30.0 # the saturation value of IMU's acceleration. not related to the units
    satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
    acc_norm: 9.81 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
    lidar_meas_cov: 0.01 # 0.001
    acc_cov_output: 500
    gyr_cov_output: 1000 
    b_acc_cov: 6.4356659353532566e-05
    b_gyr_cov: 3.5640318696367613e-05
    imu_meas_acc_cov: 0.1 #0.1 # 2
    imu_meas_omg_cov: 0.1 #0.1 # 2 
    gyr_cov_input: 1.5636343949698187e-03 # for IMU as input model
    acc_cov_input: 3.9939570888238808e-03 # for IMU as input model
    plane_thr: 0.1 # 0.05, the threshold for plane criteria, the smaller, the flatter a plane
    match_s: 81
    ivox_grid_resolution: 2.0
    dis_thre: 5.0 # 最近邻搜索的距离阈值
    gravity: [0.0, 0.0, -9.810] # [-0.30, 0.880, -9.76] # liosam [0.0, 9.810, 0.0] # # preknown gravity, use when imu_en is false or start from a non-stationary state
    gravity_init: [0.0, 0.0, -9.810] # preknown gravity in the initial IMU frame for unstationary start or in the initial LiDAR frame for using without IMU
    extrinsic_T: [ 0.8105439035, -0.3070543592, 0.8027240583 ]
    extrinsic_R: [ 9.999976e-01, -7.854027e-04, 2.024406e-03,
                7.553071e-04, 9.998898e-01, 1.482454e-02,
                -2.035826e-03, -1.482298e-02, 9.998881e-01 ]
    # extrinsic_T: [ 0, 0, 0.28] # ulhk # [-0.5, 1.4, 1.5] # utbm
    # extrinsic_R: [ 0, 1, 0,
    #                -1, 0, 0,
    #                0, 0, 1 ] # ulhk 5 6
    # extrinsic_R: [ 0, -1, 0,
    #                 1, 0, 0,
    #                 0, 0, 1 ] # utbm 1, 2
    #extrinsic_R: [ 1, 0, 0,
    #               0, 1, 0,
    #               0, 0, 1 ] # ulhk 4 utbm 3

odometry: 
    publish_odometry_without_downsample: false

publish:
    path_en: true                 # false: close the path output
    dense_publish_en: true        # true: use dense undistorted cloud for publishing
    scan_publish_en: true         # false: close all the point cloud output
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
